version: '3.3'
services:
  wex:
    container_name: wex_app
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
     - api
    entrypoint:
      - /app/wex
    restart: always
    depends_on:
      - wex_db
    ports:
      - "8080:8080"
    networks:
      - postgres-network
    environment:
      - DB_URL=postgresql://wex:pass@wex_db/wex_test?sslmode=disable

  migrate:
    image: migrate/migrate:v4.15.2
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://wex:pass@wex_db/wex_test?sslmode=disable",
      ]
    command: ["up"]
    networks:
      - postgres-network
    depends_on:
      - wex_db
    restart: on-failure

  wex_db:
    image: postgres
    container_name: wex_db
    restart: always
    environment:
      - POSTGRES_USER=wex
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=wex_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
