version: '3.3'
services:
  # wex_app:
  #   container_name: wex_app
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   depends_on:
  #     - wex_db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - postgres-network
  #   environment:
  #     - DB_URL=postgresql://wex:pass@wex_db/wex_test?sslmode=disable

  wex_db:
    image: postgres
    container_name: wex_db
    restart: always
    environment:
      - POSTGRES_USER=wex
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=wex_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
