// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	fiscaldata "github.com/heronvitor/pkg/dataaccess/clients/fiscaldata"
	mock "github.com/stretchr/testify/mock"
)

// ExchangeRatesClient is an autogenerated mock type for the ExchangeRatesClient type
type ExchangeRatesClient struct {
	mock.Mock
}

// GetAllExchangeRates provides a mock function with given fields:
func (_m *ExchangeRatesClient) GetAllExchangeRates() ([]fiscaldata.ExchangeRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllExchangeRates")
	}

	var r0 []fiscaldata.ExchangeRate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]fiscaldata.ExchangeRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []fiscaldata.ExchangeRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fiscaldata.ExchangeRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExchangeRatesClient creates a new instance of ExchangeRatesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangeRatesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangeRatesClient {
	mock := &ExchangeRatesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
