name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Import env-file       
      uses: cardinalby/export-env-action@v1
      with:
        envFile: '.env'    
        expand: 'true'

    - name: Setup db
      run: docker-compose up --build -d
    
    - name: Create Tables
      run: make migrate-up

    - name: Run test
      run: go test ./...

