name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Run test
      run: go test ./...

